apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketchat-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketchat-server
  template:
    metadata:
      labels:
        app: rocketchat-server
    spec:
      containers:
        - name: rocketchat-server
          image: rocketchat/rocket.chat:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/mydb
            - name: MONGO_OPLOG_URL
              value: mongodb://mongo:27017/local
          imagePullPolicy: Always
